apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypyhwjser-deploy
  labels:
    app: mypyhwjser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypyhwjser
  template:
    metadata:
      labels:
        app: mypyhwjser
    spec:
      containers:
      - name: mypyhwjser
        image: kyuzom/pyhwjser:0.0.4
        ports:
        - containerPort: 5001   # custom port defined inside Dockerfile
